---
toc: true
---

<table class="table-striped text-left table-bordered" align = "center">

  <thead>
    <th style="width:  11%">Date</th>
    <th style="width:  30%">Description</th>
    <th style="width:  25%">Notes</th>
    <th style="width:  15%">Links</th>
  </thead>


  <tr>
    <td><input type="checkbox" />Sep 30</td>
    <td> Introduction to Data &nbsp; &nbsp; </td>
    <td></td>
    <td><a href="https://mdogucu.github.io/stats67-fa25-starter-codes/1disa-intro-data.qmd" download> <i class="fa-brands fa-r-project" aria-hidden="true"
            title="Download Quarto File" target = "_blank"></i></a>
        <a href="https://mdogucu.github.io/stats67-fa25-starter-codes/1disa-intro-data-TA-notes.qmd" download title="TA notes"> TA notes</a></td>
  </tr>
  
  <tr>
    <td><input type="checkbox" />Oct 7</td>
    <td> Summarizing Data and Study Design &nbsp; &nbsp; </td>
    <td></td>
    <td><a href="https://mdogucu.github.io/stats67-fa25-starter-codes/2disa-study-prob.qmd" download> <i class="fa-brands fa-r-project" aria-hidden="true"
            title="Download Quarto File" target = "_blank"></i></a>
            <a href="https://mdogucu.github.io/stats67-fa25-starter-codes/2disa-study-prob-TA-notes.qmd" download title="TA notes"> TA notes</a></td>
  </tr>
  
  <tr>
    <td><input type="checkbox" />Oct 14</td>
    <td> Probability and Discrete Random Variables &nbsp; &nbsp; </td>
    <td></td>
    <td><a href="https://mdogucu.github.io/stats67-fa25-starter-codes/3disa-prob-discrete-rv.qmd" download> <i class="fa-brands fa-r-project" aria-hidden="true"
            title="Download Quarto File" target = "_blank"></i></a>
            <a href="https://mdogucu.github.io/stats67-fa25-starter-codes/3disa-prob-discrete-rv-TA-notes.qmd" download title="TA notes"> TA notes</a></td>
  </tr>
  
  <tr>
    <td><input type="checkbox" />Oct 21</td>
    <td> Discrete Distributions and Continuous Random Variables &nbsp; &nbsp; </td>
    <td></td>
    <td><a href="https://mdogucu.github.io/stats67-fa25-starter-codes/4disa-discrete-distr-continuous-rv.qmd" download> <i class="fa-brands fa-r-project" aria-hidden="true"
            title="Download Quarto File" target = "_blank"></i></a>
            <a href="https://mdogucu.github.io/stats67-fa25-starter-codes/4disa-discrete-distr-continuous-rv-TA-notes.qmd" download title="TA notes"> TA notes</a></td>
  </tr>
  
  <tr>
    <td><input type="checkbox" />Oct 28</td>
    <td> Continuous Distributions and Midterm Review &nbsp; &nbsp; </td>
    <td><a href="https://docs.google.com/presentation/d/1XhZwyuECilOtk5HQqyLgw2LasBefCBfPLjrIheMyEK0/edit?usp=sharing" target ="_blank"> <i class="fas fa-laptop" aria-hidden="true"
            title="External Link to Slides" target = "_blank"></i></td>
    <td><a href="https://mdogucu.github.io/stats67-fa25-starter-codes/5disa-continuous-distr.qmd" download> <i class="fa-brands fa-r-project" aria-hidden="true"
            title="Download Quarto File" target = "_blank"></i></a>
            <a href="https://mdogucu.github.io/stats67-fa25-starter-codes/5disa-continuous-distr-TA-notes.qmd" download title="TA notes"> TA notes</a></td>
  </tr>

  <tr>
    <td><input type="checkbox" />Nov 4</td>
    <td> Introduction to Statistical Inference and Midterm Solutions &nbsp; &nbsp; </td>
    <td><a href="https://canvas.eee.uci.edu/courses/76405/files?preview=33105761" target ="_blank" title="External Link to Canvas"> Midterm Solutions </a></td>
    <td><a href="https://mdogucu.github.io/stats67-fa25-starter-codes/6disa-stat-inf-intro.qmd" download> <i class="fa-brands fa-r-project" aria-hidden="true"
            title="Download Quarto File" target = "_blank"></i></a>
            <a href="https://mdogucu.github.io/stats67-fa25-starter-codes/6disa-stat-inf-TA-notes.qmd" download title="TA notes"> TA notes</a></td>
  </tr>
  
  <tr>
    <td><input type="checkbox" /> Nov 11 </td>
    <td> Inference for a Single Proportion and Difference Between 2 Proportions &nbsp; &nbsp; </td>
    <td> <mark> NO DISCUSSION TODAY: Veteran's day holiday</mark> <br> Instead here is a <a href="https://urldefense.com/v3/__https://uci.zoom.us/rec/share/IaZOLKxdct5EB-q12UxvkGBjMTt55SC2CuR3S_s36yeFB7kTDGvPzdj0ArnA6Scs.3ZfRJqM6RjUVkglf__;!!CzAuKJ42GuquVTTmVmPViYEvSg!JJb9QWGhSdgSqqKH0ZNKih99EkoaBEk_nC2nYS0-TIJvR-d9uyYbX-sHR8Bkd-YUYvML6lw0VXkfv3g$" target ="_blank" title="Link to Zoom Recording"> recording </a> of Lynn going over Single Proportions. Peter's recording for 2 Proportions is <a href="https://uci.zoom.us/rec/share/NIAV7RBcFapwSaJqQnumcUUY_U4kEfd_Uhc1M3anWoT0flbF57YYjZ31-RWi8Eeu.4WjGWqvyOCZF9LNq?startTime=1763059878000" target ="_blank" title="Link to Zoom Recording"> here</a>.</td>
    <td><a href="https://mdogucu.github.io/stats67-fa25-starter-codes/7disa-single-diff-props.qmd" download> <i class="fa-brands fa-r-project" aria-hidden="true"
            title="Download Quarto File" target = "_blank"></i></a>
            <a href="https://mdogucu.github.io/stats67-fa25-starter-codes/7disa-single-diff-props-TA-notes.qmd" download title="TA notes"> TA notes</a></td>
  </tr>
  
  <tr>
    <td><input type="checkbox" />Nov 18</td>
    <td> Inference for Difference Between 2 Proportions and for a Single Mean &nbsp; &nbsp; </td>
    <td></td>
    <td><a href="https://mdogucu.github.io/stats67-fa25-starter-codes/8disa-diff-props-single-mean.qmd" download> <i class="fa-brands fa-r-project" aria-hidden="true"
            title="Download Quarto File" target = "_blank"></i></a>
            <a href="https://mdogucu.github.io/stats67-fa25-starter-codes/8disa-diff-props-single-mean-TA-notes.qmd" download title="TA notes"> TA notes</a></td>
  </tr>
  
  <tr>
    <td><input type="checkbox" />Nov 25</td>
    <td> Inference for Difference Between 2 Means and Simple Linear Regression &nbsp; &nbsp; </td>
    <td> <a href="https://urldefense.com/v3/__https://uci.zoom.us/rec/share/RX_5LvLdMdOxJDPa8rBThlDT9LCi9t8vgCbxn1ym5RaKbolbHK4CEOamcbSJvISy.r3Bdc9vhSMEZrjZr__;!!CzAuKJ42GuquVTTmVmPViYEvSg!MPONn_VNk8pJO_g9-Ejsaidobm54siYkhBvWgOf0zsaO2HqPkI5eysI6NIbJGYDRFNwhzbTXBgiime0$" target ="_blank" title="Link to Zoom Recording"> Recording </a> <br> Note: In the recording, I accidentally wrote \\hat{eruptions}, but it should be just eruptions. </td>
    <td><a href="https://mdogucu.github.io/stats67-fa25-starter-codes/9disa-diff-mean-simple-linear-regression.qmd" download> <i class="fa-brands fa-r-project" aria-hidden="true"
            title="Download Quarto File" target = "_blank"></i></a>
            <a href="https://mdogucu.github.io/stats67-fa25-starter-codes/9disa-diff-mean-simple-linear-regression-TA-notes.qmd" download title="TA notes"> TA notes</a></td>
  </tr>
        
</table>
